version: '3.1'
services:
  odoo:
    image: odoo:17.0
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/addons
      - ./odoo.conf:/etc/odoo/odoo.conf
    environment:
      - HOST=postgres
    external_links:
      - postgres
    networks:
      - test_network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5432:5432"
    networks:
      - test_network

networks:
  test_network:
    external: True
